### PR TITLE
Add multiple browsers suppport

### LINKED ISSUE #19: Multiple browsers
Hi,

Laravel dusk allows to create more then one browser like this

```php
$this->browse(function ($first, $second) {
    $first->loginAs(User::find(1))
          ->visit('/home')
          ->waitForText('Message');

    $second->loginAs(User::find(2))
           ->visit('/home')
           ->waitForText('Message')
           ->type('message', 'Hey Taylor')
           ->press('Send');

    $first->waitForText('Hey Taylor')
          ->assertSee('Jeffrey Way');
});
```

This is not possible in laravel zero due to always passing one browser in 
https://github.com/nunomaduro/laravel-console-dusk/blob/9ae9a9a47944f8490b7a6d6a25e0d01405fd8545/src/Manager.php#L30-L35

### PR DESCRIPTION
**Pull request by manelgavalda**
Based on the official `laravel/dusk` implementation: 
https://github.com/laravel/dusk/blob/6.x/src/Concerns/ProvidesBrowser.php

Fix #19

### CODE REVIEW

**Comment by owenvoke** [comment]
Going to test this later today. Just to check, is this backwards compatible? :+1:

**Comment by manelgavalda** [comment]
Thanks @owenvoke 👍
Yes, you can pass only one browser like before.

**Review by owenvoke — APPROVED** [review]
LGTM! 👍🏻 @nunomaduro, what do you think?

I guess we can also type-hint the `createBrowsers()` method as:
```php
/** @return Collection<ConsoleBrowserContract> */
protected function createBrowsers(Command $command, Closure $callback): Collection
```

**Comment by manelgavalda** [comment]
Cool, just added the docblock and the type-hint 😀

**Pull request merged**
